import "fake-indexeddb/auto";
import { beforeEach, describe, expect, it } from "vitest";
import { db } from "../src/lib/db";
import { tallySheets, migrationMap, migrationPreview, importMigration, undoMigration, type MappedSheet } from "../src/lib/migration";
import { setScope, MAIN_STORE } from "../src/lib/scope";
beforeEach(async () => { setScope(MAIN_STORE, "owner"); await Promise.all(db.tables.map(t => t.clear())); });
const items = (): MappedSheet => ({ kind: "products", headers: [], rows: [["101", "CHAIN", "PCS", "120", "7117", "metal", "Wedding"]], map: { item_code: 0, item: 1, unit: 2, rate: 3, hsn: 4, material: 5, collection: 6 } });
const stock = (): MappedSheet => ({ kind: "stock", headers: [], rows: [["101", "R1", "10"]], map: { item_code: 0, rack: 1, qty: 2 } });
describe("migration wizard", () => {
  it("imports Tally masters and supplier/customer debit-credit balances", () => { const xml = '<ENVELOPE><TALLYMESSAGE><STOCKITEM NAME="Chain"><BASEUNITS>Nos</BASEUNITS><OPENINGBALANCE>5 Nos</OPENINGBALANCE><OPENINGRATE>120/Nos</OPENINGRATE><HSNCODE>7117</HSNCODE></STOCKITEM><LEDGER NAME="Customer"><PARENT>Sundry Debtors</PARENT><OPENINGBALANCE>-500</OPENINGBALANCE></LEDGER><LEDGER NAME="Supplier"><PARENT>Sundry Creditors</PARENT><OPENINGBALANCE>1000</OPENINGBALANCE></LEDGER></TALLYMESSAGE></ENVELOPE>'; const sheets = tallySheets(xml); expect(sheets.map(s => s.kind)).toEqual(["products", "parties", "stock"]); expect(sheets[1].rows[0][7]).toBe(500); expect(sheets[1].rows[1][7]).toBe(1000); expect(sheets[2].rows[0][3]).toBe(5); expect(migrationMap(sheets[0]).hsn).toBe(4); });
  it("rejects XML entities and duplicate source items before writes", async () => { expect(() => tallySheets('<!DOCTYPE x [<!ENTITY secret SYSTEM "file:///etc/passwd">]><x/>')).toThrow("entities"); const s = items(); s.rows.push(s.rows[0]); expect((await migrationPreview([s])).issues.join()).toContain("duplicate"); await expect(importMigration([s], "items.csv", "o")).rejects.toThrow("duplicate"); expect(await db.products.count()).toBe(0); });
  it("imports items, racks and opening stock atomically then undoes them", async () => { const batch = await importMigration([items(), stock()], "opening.csv", "o"); expect(batch.changes.length).toBe(3); const p = (await db.products.toArray())[0]; expect(p).toMatchObject({ rate: 12000, hsn: "7117", material: "metal", collection: "Wedding" }); expect((await db.stock.toArray())[0].qty).toBe(10); await undoMigration(); expect((await db.stock.toArray())[0].qty).toBe(0); expect((await db.products.get(p.id))?.deleted).toBe(1); await expect(undoMigration()).rejects.toThrow("No import"); });
  it("rolls back all writes when opening stock references an unknown item", async () => { const s = stock(); s.rows = [["MISSING", "R1", 10]]; await expect(importMigration([items(), s], "broken.csv", "o")).rejects.toThrow("not found"); expect(await db.products.count()).toBe(0); expect(await db.import_batches.count()).toBe(0); expect(await db.outbox.count()).toBe(0); });
  it("restores an updated master and refuses undo after later edits", async () => { await importMigration([items()], "first.csv", "o"); const next = items(); next.rows[0][3] = "200"; await importMigration([next], "update.csv", "o"); await undoMigration(); expect((await db.products.toArray())[0].rate).toBe(12000); const batch = await importMigration([next], "update2.csv", "o"); const p = (await db.products.toArray())[0]; await db.products.update(p.id, { rate: 30000 }); await expect(undoMigration()).rejects.toThrow("changed after import"); expect((await db.import_batches.get(batch.id))?.undone).not.toBe(true); });
});
